"""FastAPI service: the Flash Dental grounded copilot, v1 shape.

Single responsibility: the HTTP edge. It wires the pure retrieval, grounding,
redaction, and KPI core to /ask, /health, and the preset endpoints — nothing more.
The corpus is small and read-only, so it is indexed once at import.
"""
from __future__ import annotations

from typing import Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from flash_dental_copilot.corpus import (
    DomainCorpus,
    available_domain_names,
    load_domain_corpus,
)
from flash_dental_copilot.employee_records import load_employees
from flash_dental_copilot.grounding import (
    ABSTAIN_SIMILARITY_THRESHOLD,
    GroundedAnswer,
    select_grounded_answer,
)
from flash_dental_copilot.intent_reranking import reorder_by_intent
from flash_dental_copilot.pii_redaction import redact_personally_identifiable_information
from flash_dental_copilot.question_router import answer_analytical_question
from flash_dental_copilot.answer_policy import (
    REFUSAL_TEXT,
    asks_for_sensitive_personal_data,
    visualization_for_citation,
)
from flash_dental_copilot.retrieval import rank_indexed_documents_by_relevance
from flash_dental_copilot.schemas import AskRequest, AskResponse
from flash_dental_copilot.service_records import (
    build_domain_kpi_summary,
    load_maintenance_schedule,
    load_service_tickets,
)

# A fixed report used to demonstrate PII de-identification on every answer.
PII_MASKING_EXAMPLE_REPORT = (
    "Report: Yudi Pratama serviced serial FD-1042; contact 0812-3456-7890."
)

application = FastAPI(title="Flash Dental Copilot", version="1.0.0")

# The demo deck is a static site on another origin; the API is read-only, so any
# origin may call it. Tighten allow_origins to the deck's URL for a real client.
application.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)

_DOMAIN_CORPORA: dict[str, DomainCorpus] = {
    domain_name: load_domain_corpus(domain_name)
    for domain_name in available_domain_names()
}
_SERVICE_TICKETS = load_service_tickets()
_MAINTENANCE_SCHEDULE = load_maintenance_schedule()
_EMPLOYEES = load_employees()


@application.get("/health")
def report_health() -> dict[str, str]:
    """Liveness probe for Cloud Run."""
    return {"status": "ok"}


@application.get("/domains")
def list_domains() -> dict[str, list[str]]:
    """The domains the copilot can answer over."""
    return {"domains": available_domain_names()}


@application.get("/domains/{domain_name}/presets")
def list_preset_questions(domain_name: str) -> dict:
    """The example questions the demo offers for a domain."""
    corpus = _require_domain_corpus(domain_name)
    return {"domain": domain_name, "preset_questions": corpus.preset_questions}


@application.post("/ask", response_model=AskResponse)
def answer_question(ask_request: AskRequest) -> AskResponse:
    """Compute the answer for an aggregate question; else retrieve, ground, and abstain."""
    _require_domain_corpus(ask_request.domain)
    pii_masking = redact_personally_identifiable_information(PII_MASKING_EXAMPLE_REPORT)
    shared_fields = dict(
        domain=ask_request.domain,
        question=ask_request.question,
        kpi_summary=build_domain_kpi_summary(ask_request.domain, _SERVICE_TICKETS),
        pii_masking_example=pii_masking.redacted_text,
        computed_by_code_note="Numbers are computed by code, not generated by the model.",
    )

    computed_answer = answer_analytical_question(
        ask_request.question, _SERVICE_TICKETS, _MAINTENANCE_SCHEDULE, _EMPLOYEES
    )
    if computed_answer is not None:
        return AskResponse(
            **shared_fields, answer_kind="computed", abstained=False, similarity_score=1.0,
            answer_text=computed_answer.answer_text, citation_document_id=None,
            computation_detail=computed_answer.computation_detail,
            visualization=computed_answer.visualization,
        )

    if asks_for_sensitive_personal_data(ask_request.question):
        return AskResponse(
            **shared_fields, answer_kind="abstained", abstained=True, similarity_score=0.0,
            answer_text=REFUSAL_TEXT, citation_document_id=None, computation_detail=None,
        )

    grounded_answer, hint_domain = _route_within_or_across_domains(
        ask_request.domain, ask_request.question
    )
    if grounded_answer.abstained:
        return AskResponse(
            **shared_fields, answer_kind="abstained", abstained=True,
            similarity_score=round(grounded_answer.similarity_score, 3),
            answer_text=grounded_answer.answer_text
            + _format_cross_domain_hint(ask_request.domain, hint_domain),
            citation_document_id=None, computation_detail=None,
        )
    return AskResponse(
        **shared_fields, answer_kind="retrieved", abstained=False,
        similarity_score=round(grounded_answer.similarity_score, 3),
        answer_text=grounded_answer.answer_text,
        citation_document_id=grounded_answer.citation_document_id, computation_detail=None,
        visualization=visualization_for_citation(grounded_answer.citation_document_id),
    )


# A question belongs to another view when its best match there is this much stronger.
_CROSS_DOMAIN_DOMINANCE = 1.3


def _score_and_ground(domain_name: str, question: str) -> tuple[float, GroundedAnswer]:
    """Return the top similarity score and the grounded answer for one domain."""
    corpus = _DOMAIN_CORPORA[domain_name]
    ranked_documents = rank_indexed_documents_by_relevance(
        question, corpus.indexed_documents, corpus.inverse_document_frequencies
    )
    ranked_documents = reorder_by_intent(question, ranked_documents)
    top_score = ranked_documents[0].similarity_score if ranked_documents else 0.0
    return top_score, select_grounded_answer(ranked_documents)


def _route_within_or_across_domains(
    current_domain: str, question: str
) -> tuple[GroundedAnswer, Optional[str]]:
    """Answer in the current view, or abstain-and-point when the question fits another view."""
    current_score, current_answer = _score_and_ground(current_domain, question)
    best_other_domain: Optional[str] = None
    best_other_score = 0.0
    for other_domain in _DOMAIN_CORPORA:
        if other_domain == current_domain:
            continue
        other_score, _ = _score_and_ground(other_domain, question)
        if other_score > best_other_score:
            best_other_domain, best_other_score = other_domain, other_score
    other_view_dominates = (
        best_other_domain is not None
        and best_other_score >= ABSTAIN_SIMILARITY_THRESHOLD
        and best_other_score > max(current_score, 0.01) * _CROSS_DOMAIN_DOMINANCE
    )
    if other_view_dominates:
        forced_abstention = GroundedAnswer(
            abstained=True, similarity_score=current_score,
            answer_text="Not in this view's records.", citation_document_id=None,
        )
        return forced_abstention, best_other_domain
    if current_answer.abstained and best_other_score >= ABSTAIN_SIMILARITY_THRESHOLD:
        return current_answer, best_other_domain
    return current_answer, None


def _format_cross_domain_hint(current_domain: str, hint_domain: Optional[str]) -> str:
    """Phrase the 'switch tabs' hint, tying it to RBAC scoping."""
    if hint_domain is None:
        return ""
    return (
        f" That looks like a question for the {hint_domain} view — this {current_domain} "
        f"view is scoped to its own records (RBAC). Switch tabs to ask it."
    )


def _require_domain_corpus(domain_name: str) -> DomainCorpus:
    """Return the indexed corpus for a domain, or a 404 if it is unknown."""
    corpus = _DOMAIN_CORPORA.get(domain_name)
    if corpus is None:
        raise HTTPException(status_code=404, detail=f"Unknown domain: {domain_name}")
    return corpus
