"""FastAPI service: the Flash Dental grounded copilot, v1 shape.

Single responsibility: the HTTP edge. It wires the pure retrieval, grounding,
redaction, and KPI core to /ask, /health, and the preset endpoints — nothing more.
The corpus is small and read-only, so it is indexed once at import.
"""
from __future__ import annotations

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from flash_dental_copilot.corpus import (
    DomainCorpus,
    available_domain_names,
    load_domain_corpus,
)
from flash_dental_copilot.grounding import select_grounded_answer
from flash_dental_copilot.pii_redaction import redact_personally_identifiable_information
from flash_dental_copilot.retrieval import rank_indexed_documents_by_relevance
from flash_dental_copilot.schemas import AskRequest, AskResponse
from flash_dental_copilot.service_records import (
    build_domain_kpi_summary,
    load_service_tickets,
)

# A fixed report used to demonstrate PII de-identification on every answer.
PII_MASKING_EXAMPLE_REPORT = (
    "Report: Yudi Pratama serviced serial FD-1042; contact 0812-3456-7890."
)

application = FastAPI(title="Flash Dental Copilot", version="1.0.0")

# The demo deck is a static site on another origin; the API is read-only, so any
# origin may call it. Tighten allow_origins to the deck's URL for a real client.
application.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)

_DOMAIN_CORPORA: dict[str, DomainCorpus] = {
    domain_name: load_domain_corpus(domain_name)
    for domain_name in available_domain_names()
}
_SERVICE_TICKETS = load_service_tickets()


@application.get("/health")
def report_health() -> dict[str, str]:
    """Liveness probe for Cloud Run."""
    return {"status": "ok"}


@application.get("/domains")
def list_domains() -> dict[str, list[str]]:
    """The domains the copilot can answer over."""
    return {"domains": available_domain_names()}


@application.get("/domains/{domain_name}/presets")
def list_preset_questions(domain_name: str) -> dict:
    """The example questions the demo offers for a domain."""
    corpus = _require_domain_corpus(domain_name)
    return {"domain": domain_name, "preset_questions": corpus.preset_questions}


@application.post("/ask", response_model=AskResponse)
def answer_question(ask_request: AskRequest) -> AskResponse:
    """Retrieve, ground, cite, abstain when weak, and attach a computed KPI."""
    corpus = _require_domain_corpus(ask_request.domain)
    ranked_documents = rank_indexed_documents_by_relevance(
        ask_request.question,
        corpus.indexed_documents,
        corpus.inverse_document_frequencies,
    )
    grounded_answer = select_grounded_answer(ranked_documents)
    pii_masking = redact_personally_identifiable_information(PII_MASKING_EXAMPLE_REPORT)
    return AskResponse(
        domain=ask_request.domain,
        question=ask_request.question,
        abstained=grounded_answer.abstained,
        similarity_score=round(grounded_answer.similarity_score, 3),
        answer_text=grounded_answer.answer_text,
        citation_document_id=grounded_answer.citation_document_id,
        kpi_summary=build_domain_kpi_summary(ask_request.domain, _SERVICE_TICKETS),
        pii_masking_example=pii_masking.redacted_text,
        computed_by_code_note="KPIs computed by code, not generated by the model.",
    )


def _require_domain_corpus(domain_name: str) -> DomainCorpus:
    """Return the indexed corpus for a domain, or a 404 if it is unknown."""
    corpus = _DOMAIN_CORPORA.get(domain_name)
    if corpus is None:
        raise HTTPException(status_code=404, detail=f"Unknown domain: {domain_name}")
    return corpus
