"""Compute operational KPIs deterministically from structured service tickets.

Single responsibility: the numbers. Every KPI here is computed by code, never
generated by the model — the model only ever explains a number it did not invent.
A KPI whose inputs are missing returns None rather than a misleading zero.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import date


@dataclass(frozen=True)
class ServiceTicket:
    """One completed or open service job, with the fields the KPIs need."""
    ticket_id: str
    unit_serial: str
    technician_name: str
    was_fixed_first_visit: bool
    cycle_time_days: int
    status: str
    job_category: str = "service"
    clinic_name: str = ""
    city: str = ""
    unit_model: str = ""
    hold_reason: str = ""


def _round_to_one_decimal(value: float) -> float:
    return round(value, 1)


def compute_first_time_fix_rate_percent(
    service_tickets: list[ServiceTicket],
) -> float | None:
    """Share of completed jobs resolved on the first visit, as a percentage."""
    completed_tickets = [ticket for ticket in service_tickets if ticket.status == "finished"]
    if not completed_tickets:
        return None
    first_visit_fixes = sum(1 for ticket in completed_tickets if ticket.was_fixed_first_visit)
    return _round_to_one_decimal(100.0 * first_visit_fixes / len(completed_tickets))


def compute_average_cycle_time_days(
    service_tickets: list[ServiceTicket],
) -> float | None:
    """Mean report-to-service gap across completed jobs, in days."""
    completed_tickets = [ticket for ticket in service_tickets if ticket.status == "finished"]
    if not completed_tickets:
        return None
    total_cycle_days = sum(ticket.cycle_time_days for ticket in completed_tickets)
    return _round_to_one_decimal(total_cycle_days / len(completed_tickets))


def compute_technician_first_time_fix_rate_percent(
    service_tickets: list[ServiceTicket], technician_name: str
) -> float | None:
    """First-time-fix percentage for one technician's completed jobs."""
    technician_tickets = [
        ticket
        for ticket in service_tickets
        if ticket.technician_name == technician_name and ticket.status == "finished"
    ]
    return compute_first_time_fix_rate_percent(technician_tickets)


def count_outstanding_jobs(service_tickets: list[ServiceTicket]) -> int:
    """How many jobs are still open (not finished, not cancelled)."""
    return sum(
        1
        for ticket in service_tickets
        if ticket.status not in ("finished", "cancelled")
    )


def compute_warranty_expiry_date(
    purchase_date_iso: str, warranty_years: int
) -> str:
    """Add whole years to an ISO purchase date; the warranty end date, as ISO text."""
    purchase_date = date.fromisoformat(purchase_date_iso)
    try:
        expiry_date = purchase_date.replace(year=purchase_date.year + warranty_years)
    except ValueError:
        # 29 Feb purchase in a non-leap expiry year falls back to 28 Feb.
        expiry_date = purchase_date.replace(
            year=purchase_date.year + warranty_years, day=28
        )
    return expiry_date.isoformat()
